stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    outs:
    - data/raw
  data_validation:
    cmd: python src/data/data_validation.py
    deps:
    - data/raw
    - src/data/data_validation.py
    outs:
    - data/processed

  model_building:
    cmd: python src/model/model_building.py
    deps:
    - data/processed
    - src/model/model_building.py
    outs:
    - model.pkl

  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
    - model.pkl
    - src/model/model_evaluation.py
    metrics:
    - metrics.json
